app:
  port: 7899
  host: 0.0.0.0
  grpcServer:
    host: localhost
    port: 9999

  services:
    "gateway":
      host: localhost
      port: 9000
    "user":
      host: localhost
      port: 9001
    "candle_stick":
      host: localhost
      port: 9002
    "order":
      host: localhost
      port: 9003
    "pnl":
      host: localhost
      port: 9004
    "token":
      host: localhost
      port: 9005
    "pair":
      host: localhost
      port: 9006
    "wallet":
      host: localhost
      port: 9007

