app:
  port: 7899
  host: 0.0.0.0
  grpcServer:
    host: localhost
    port: 9999

  services:
    "gateway":
      host: localhost
      port: 9001
    "user":
      host: localhost
      port: 9002
    "pnl":
      host: localhost
      port: 9004
