// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: candle.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Candle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pair          string                 `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	TimeFrame     string                 `protobuf:"bytes,2,opt,name=time_frame,json=timeFrame,proto3" json:"time_frame,omitempty"`
	Open          string                 `protobuf:"bytes,3,opt,name=open,proto3" json:"open,omitempty"`
	High          string                 `protobuf:"bytes,4,opt,name=high,proto3" json:"high,omitempty"`
	Low           string                 `protobuf:"bytes,5,opt,name=low,proto3" json:"low,omitempty"`
	Close         string                 `protobuf:"bytes,6,opt,name=close,proto3" json:"close,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candle) Reset() {
	*x = Candle{}
	mi := &file_candle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candle) ProtoMessage() {}

func (x *Candle) ProtoReflect() protoreflect.Message {
	mi := &file_candle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candle.ProtoReflect.Descriptor instead.
func (*Candle) Descriptor() ([]byte, []int) {
	return file_candle_proto_rawDescGZIP(), []int{0}
}

func (x *Candle) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *Candle) GetTimeFrame() string {
	if x != nil {
		return x.TimeFrame
	}
	return ""
}

func (x *Candle) GetOpen() string {
	if x != nil {
		return x.Open
	}
	return ""
}

func (x *Candle) GetHigh() string {
	if x != nil {
		return x.High
	}
	return ""
}

func (x *Candle) GetLow() string {
	if x != nil {
		return x.Low
	}
	return ""
}

func (x *Candle) GetClose() string {
	if x != nil {
		return x.Close
	}
	return ""
}

type GetCandlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pair          string                 `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	TimeFrame     string                 `protobuf:"bytes,2,opt,name=time_frame,json=timeFrame,proto3" json:"time_frame,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandlesRequest) Reset() {
	*x = GetCandlesRequest{}
	mi := &file_candle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandlesRequest) ProtoMessage() {}

func (x *GetCandlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_candle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandlesRequest.ProtoReflect.Descriptor instead.
func (*GetCandlesRequest) Descriptor() ([]byte, []int) {
	return file_candle_proto_rawDescGZIP(), []int{1}
}

func (x *GetCandlesRequest) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *GetCandlesRequest) GetTimeFrame() string {
	if x != nil {
		return x.TimeFrame
	}
	return ""
}

type GetCandlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candles       []*Candle              `protobuf:"bytes,1,rep,name=candles,proto3" json:"candles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandlesResponse) Reset() {
	*x = GetCandlesResponse{}
	mi := &file_candle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandlesResponse) ProtoMessage() {}

func (x *GetCandlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_candle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandlesResponse.ProtoReflect.Descriptor instead.
func (*GetCandlesResponse) Descriptor() ([]byte, []int) {
	return file_candle_proto_rawDescGZIP(), []int{2}
}

func (x *GetCandlesResponse) GetCandles() []*Candle {
	if x != nil {
		return x.Candles
	}
	return nil
}

type GetCandleStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pair          string                 `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	TimeFrame     string                 `protobuf:"bytes,2,opt,name=time_frame,json=timeFrame,proto3" json:"time_frame,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandleStatsRequest) Reset() {
	*x = GetCandleStatsRequest{}
	mi := &file_candle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandleStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandleStatsRequest) ProtoMessage() {}

func (x *GetCandleStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_candle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandleStatsRequest.ProtoReflect.Descriptor instead.
func (*GetCandleStatsRequest) Descriptor() ([]byte, []int) {
	return file_candle_proto_rawDescGZIP(), []int{3}
}

func (x *GetCandleStatsRequest) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *GetCandleStatsRequest) GetTimeFrame() string {
	if x != nil {
		return x.TimeFrame
	}
	return ""
}

type GetCandleStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candles       []*Candle              `protobuf:"bytes,1,rep,name=candles,proto3" json:"candles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandleStatsResponse) Reset() {
	*x = GetCandleStatsResponse{}
	mi := &file_candle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandleStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandleStatsResponse) ProtoMessage() {}

func (x *GetCandleStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_candle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandleStatsResponse.ProtoReflect.Descriptor instead.
func (*GetCandleStatsResponse) Descriptor() ([]byte, []int) {
	return file_candle_proto_rawDescGZIP(), []int{4}
}

func (x *GetCandleStatsResponse) GetCandles() []*Candle {
	if x != nil {
		return x.Candles
	}
	return nil
}

type GetCandleLatestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pair          string                 `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	TimeFrame     string                 `protobuf:"bytes,2,opt,name=time_frame,json=timeFrame,proto3" json:"time_frame,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandleLatestRequest) Reset() {
	*x = GetCandleLatestRequest{}
	mi := &file_candle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandleLatestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandleLatestRequest) ProtoMessage() {}

func (x *GetCandleLatestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_candle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandleLatestRequest.ProtoReflect.Descriptor instead.
func (*GetCandleLatestRequest) Descriptor() ([]byte, []int) {
	return file_candle_proto_rawDescGZIP(), []int{5}
}

func (x *GetCandleLatestRequest) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *GetCandleLatestRequest) GetTimeFrame() string {
	if x != nil {
		return x.TimeFrame
	}
	return ""
}

type GetCandleLatestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candle        *Candle                `protobuf:"bytes,1,opt,name=candle,proto3" json:"candle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandleLatestResponse) Reset() {
	*x = GetCandleLatestResponse{}
	mi := &file_candle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandleLatestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandleLatestResponse) ProtoMessage() {}

func (x *GetCandleLatestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_candle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandleLatestResponse.ProtoReflect.Descriptor instead.
func (*GetCandleLatestResponse) Descriptor() ([]byte, []int) {
	return file_candle_proto_rawDescGZIP(), []int{6}
}

func (x *GetCandleLatestResponse) GetCandle() *Candle {
	if x != nil {
		return x.Candle
	}
	return nil
}

type PostCandleValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candle        *Candle                `protobuf:"bytes,1,opt,name=candle,proto3" json:"candle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostCandleValidateRequest) Reset() {
	*x = PostCandleValidateRequest{}
	mi := &file_candle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostCandleValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCandleValidateRequest) ProtoMessage() {}

func (x *PostCandleValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_candle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCandleValidateRequest.ProtoReflect.Descriptor instead.
func (*PostCandleValidateRequest) Descriptor() ([]byte, []int) {
	return file_candle_proto_rawDescGZIP(), []int{7}
}

func (x *PostCandleValidateRequest) GetCandle() *Candle {
	if x != nil {
		return x.Candle
	}
	return nil
}

type PostCandleValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostCandleValidateResponse) Reset() {
	*x = PostCandleValidateResponse{}
	mi := &file_candle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostCandleValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCandleValidateResponse) ProtoMessage() {}

func (x *PostCandleValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_candle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCandleValidateResponse.ProtoReflect.Descriptor instead.
func (*PostCandleValidateResponse) Descriptor() ([]byte, []int) {
	return file_candle_proto_rawDescGZIP(), []int{8}
}

func (x *PostCandleValidateResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

type GetCandlesAggregateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pair          string                 `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandlesAggregateRequest) Reset() {
	*x = GetCandlesAggregateRequest{}
	mi := &file_candle_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandlesAggregateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandlesAggregateRequest) ProtoMessage() {}

func (x *GetCandlesAggregateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_candle_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandlesAggregateRequest.ProtoReflect.Descriptor instead.
func (*GetCandlesAggregateRequest) Descriptor() ([]byte, []int) {
	return file_candle_proto_rawDescGZIP(), []int{9}
}

func (x *GetCandlesAggregateRequest) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

type GetCandlesAggregateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candles       []*Candle              `protobuf:"bytes,1,rep,name=candles,proto3" json:"candles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandlesAggregateResponse) Reset() {
	*x = GetCandlesAggregateResponse{}
	mi := &file_candle_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandlesAggregateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandlesAggregateResponse) ProtoMessage() {}

func (x *GetCandlesAggregateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_candle_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandlesAggregateResponse.ProtoReflect.Descriptor instead.
func (*GetCandlesAggregateResponse) Descriptor() ([]byte, []int) {
	return file_candle_proto_rawDescGZIP(), []int{10}
}

func (x *GetCandlesAggregateResponse) GetCandles() []*Candle {
	if x != nil {
		return x.Candles
	}
	return nil
}

var File_candle_proto protoreflect.FileDescriptor

const file_candle_proto_rawDesc = "" +
	"\n" +
	"\fcandle.proto\x12\x06candle\"\x8b\x01\n" +
	"\x06Candle\x12\x12\n" +
	"\x04pair\x18\x01 \x01(\tR\x04pair\x12\x1d\n" +
	"\n" +
	"time_frame\x18\x02 \x01(\tR\ttimeFrame\x12\x12\n" +
	"\x04open\x18\x03 \x01(\tR\x04open\x12\x12\n" +
	"\x04high\x18\x04 \x01(\tR\x04high\x12\x10\n" +
	"\x03low\x18\x05 \x01(\tR\x03low\x12\x14\n" +
	"\x05close\x18\x06 \x01(\tR\x05close\"F\n" +
	"\x11GetCandlesRequest\x12\x12\n" +
	"\x04pair\x18\x01 \x01(\tR\x04pair\x12\x1d\n" +
	"\n" +
	"time_frame\x18\x02 \x01(\tR\ttimeFrame\">\n" +
	"\x12GetCandlesResponse\x12(\n" +
	"\acandles\x18\x01 \x03(\v2\x0e.candle.CandleR\acandles\"J\n" +
	"\x15GetCandleStatsRequest\x12\x12\n" +
	"\x04pair\x18\x01 \x01(\tR\x04pair\x12\x1d\n" +
	"\n" +
	"time_frame\x18\x02 \x01(\tR\ttimeFrame\"B\n" +
	"\x16GetCandleStatsResponse\x12(\n" +
	"\acandles\x18\x01 \x03(\v2\x0e.candle.CandleR\acandles\"K\n" +
	"\x16GetCandleLatestRequest\x12\x12\n" +
	"\x04pair\x18\x01 \x01(\tR\x04pair\x12\x1d\n" +
	"\n" +
	"time_frame\x18\x02 \x01(\tR\ttimeFrame\"A\n" +
	"\x17GetCandleLatestResponse\x12&\n" +
	"\x06candle\x18\x01 \x01(\v2\x0e.candle.CandleR\x06candle\"C\n" +
	"\x19PostCandleValidateRequest\x12&\n" +
	"\x06candle\x18\x01 \x01(\v2\x0e.candle.CandleR\x06candle\"7\n" +
	"\x1aPostCandleValidateResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\"0\n" +
	"\x1aGetCandlesAggregateRequest\x12\x12\n" +
	"\x04pair\x18\x01 \x01(\tR\x04pair\"G\n" +
	"\x1bGetCandlesAggregateResponse\x12(\n" +
	"\acandles\x18\x01 \x03(\v2\x0e.candle.CandleR\acandles2\xc5\x03\n" +
	"\x12CandleProtoService\x12E\n" +
	"\n" +
	"GetCandles\x12\x19.candle.GetCandlesRequest\x1a\x1a.candle.GetCandlesResponse\"\x00\x12Q\n" +
	"\x0eGetCandleStats\x12\x1d.candle.GetCandleStatsRequest\x1a\x1e.candle.GetCandleStatsResponse\"\x00\x12T\n" +
	"\x0fGetCandleLatest\x12\x1e.candle.GetCandleLatestRequest\x1a\x1f.candle.GetCandleLatestResponse\"\x00\x12]\n" +
	"\x12PostCandleValidate\x12!.candle.PostCandleValidateRequest\x1a\".candle.PostCandleValidateResponse\"\x00\x12`\n" +
	"\x13GetCandlesAggregate\x12\".candle.GetCandlesAggregateRequest\x1a#.candle.GetCandlesAggregateResponse\"\x00B\x04Z\x02./b\x06proto3"

var (
	file_candle_proto_rawDescOnce sync.Once
	file_candle_proto_rawDescData []byte
)

func file_candle_proto_rawDescGZIP() []byte {
	file_candle_proto_rawDescOnce.Do(func() {
		file_candle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_candle_proto_rawDesc), len(file_candle_proto_rawDesc)))
	})
	return file_candle_proto_rawDescData
}

var file_candle_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_candle_proto_goTypes = []any{
	(*Candle)(nil),                      // 0: candle.Candle
	(*GetCandlesRequest)(nil),           // 1: candle.GetCandlesRequest
	(*GetCandlesResponse)(nil),          // 2: candle.GetCandlesResponse
	(*GetCandleStatsRequest)(nil),       // 3: candle.GetCandleStatsRequest
	(*GetCandleStatsResponse)(nil),      // 4: candle.GetCandleStatsResponse
	(*GetCandleLatestRequest)(nil),      // 5: candle.GetCandleLatestRequest
	(*GetCandleLatestResponse)(nil),     // 6: candle.GetCandleLatestResponse
	(*PostCandleValidateRequest)(nil),   // 7: candle.PostCandleValidateRequest
	(*PostCandleValidateResponse)(nil),  // 8: candle.PostCandleValidateResponse
	(*GetCandlesAggregateRequest)(nil),  // 9: candle.GetCandlesAggregateRequest
	(*GetCandlesAggregateResponse)(nil), // 10: candle.GetCandlesAggregateResponse
}
var file_candle_proto_depIdxs = []int32{
	0,  // 0: candle.GetCandlesResponse.candles:type_name -> candle.Candle
	0,  // 1: candle.GetCandleStatsResponse.candles:type_name -> candle.Candle
	0,  // 2: candle.GetCandleLatestResponse.candle:type_name -> candle.Candle
	0,  // 3: candle.PostCandleValidateRequest.candle:type_name -> candle.Candle
	0,  // 4: candle.GetCandlesAggregateResponse.candles:type_name -> candle.Candle
	1,  // 5: candle.CandleProtoService.GetCandles:input_type -> candle.GetCandlesRequest
	3,  // 6: candle.CandleProtoService.GetCandleStats:input_type -> candle.GetCandleStatsRequest
	5,  // 7: candle.CandleProtoService.GetCandleLatest:input_type -> candle.GetCandleLatestRequest
	7,  // 8: candle.CandleProtoService.PostCandleValidate:input_type -> candle.PostCandleValidateRequest
	9,  // 9: candle.CandleProtoService.GetCandlesAggregate:input_type -> candle.GetCandlesAggregateRequest
	2,  // 10: candle.CandleProtoService.GetCandles:output_type -> candle.GetCandlesResponse
	4,  // 11: candle.CandleProtoService.GetCandleStats:output_type -> candle.GetCandleStatsResponse
	6,  // 12: candle.CandleProtoService.GetCandleLatest:output_type -> candle.GetCandleLatestResponse
	8,  // 13: candle.CandleProtoService.PostCandleValidate:output_type -> candle.PostCandleValidateResponse
	10, // 14: candle.CandleProtoService.GetCandlesAggregate:output_type -> candle.GetCandlesAggregateResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_candle_proto_init() }
func file_candle_proto_init() {
	if File_candle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_candle_proto_rawDesc), len(file_candle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_candle_proto_goTypes,
		DependencyIndexes: file_candle_proto_depIdxs,
		MessageInfos:      file_candle_proto_msgTypes,
	}.Build()
	File_candle_proto = out.File
	file_candle_proto_goTypes = nil
	file_candle_proto_depIdxs = nil
}
