// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: candle_stick.proto

package __

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// CandleStickProtoServiceClient is the client API for CandleStickProtoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CandleStick service definition
type CandleStickProtoServiceClient interface {
}

type candleStickProtoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCandleStickProtoServiceClient(cc grpc.ClientConnInterface) CandleStickProtoServiceClient {
	return &candleStickProtoServiceClient{cc}
}

// CandleStickProtoServiceServer is the server API for CandleStickProtoService service.
// All implementations must embed UnimplementedCandleStickProtoServiceServer
// for forward compatibility.
//
// CandleStick service definition
type CandleStickProtoServiceServer interface {
	mustEmbedUnimplementedCandleStickProtoServiceServer()
}

// UnimplementedCandleStickProtoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCandleStickProtoServiceServer struct{}

func (UnimplementedCandleStickProtoServiceServer) mustEmbedUnimplementedCandleStickProtoServiceServer() {
}
func (UnimplementedCandleStickProtoServiceServer) testEmbeddedByValue() {}

// UnsafeCandleStickProtoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CandleStickProtoServiceServer will
// result in compilation errors.
type UnsafeCandleStickProtoServiceServer interface {
	mustEmbedUnimplementedCandleStickProtoServiceServer()
}

func RegisterCandleStickProtoServiceServer(s grpc.ServiceRegistrar, srv CandleStickProtoServiceServer) {
	// If the following call pancis, it indicates UnimplementedCandleStickProtoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CandleStickProtoService_ServiceDesc, srv)
}

// CandleStickProtoService_ServiceDesc is the grpc.ServiceDesc for CandleStickProtoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CandleStickProtoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "candle_stick.CandleStickProtoService",
	HandlerType: (*CandleStickProtoServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "candle_stick.proto",
}
