// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: discovery.proto

package __

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// DiscoveryProtoServiceClient is the client API for DiscoveryProtoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// User service definition
type DiscoveryProtoServiceClient interface {
}

type discoveryProtoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiscoveryProtoServiceClient(cc grpc.ClientConnInterface) DiscoveryProtoServiceClient {
	return &discoveryProtoServiceClient{cc}
}

// DiscoveryProtoServiceServer is the server API for DiscoveryProtoService service.
// All implementations must embed UnimplementedDiscoveryProtoServiceServer
// for forward compatibility.
//
// User service definition
type DiscoveryProtoServiceServer interface {
	mustEmbedUnimplementedDiscoveryProtoServiceServer()
}

// UnimplementedDiscoveryProtoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiscoveryProtoServiceServer struct{}

func (UnimplementedDiscoveryProtoServiceServer) mustEmbedUnimplementedDiscoveryProtoServiceServer() {}
func (UnimplementedDiscoveryProtoServiceServer) testEmbeddedByValue()                               {}

// UnsafeDiscoveryProtoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiscoveryProtoServiceServer will
// result in compilation errors.
type UnsafeDiscoveryProtoServiceServer interface {
	mustEmbedUnimplementedDiscoveryProtoServiceServer()
}

func RegisterDiscoveryProtoServiceServer(s grpc.ServiceRegistrar, srv DiscoveryProtoServiceServer) {
	// If the following call pancis, it indicates UnimplementedDiscoveryProtoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DiscoveryProtoService_ServiceDesc, srv)
}

// DiscoveryProtoService_ServiceDesc is the grpc.ServiceDesc for DiscoveryProtoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiscoveryProtoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "discovery.DiscoveryProtoService",
	HandlerType: (*DiscoveryProtoServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "discovery.proto",
}
