// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: discovery.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DiscoveryProtoService_Discovery_FullMethodName = "/discovery.DiscoveryProtoService/Discovery"
)

// DiscoveryProtoServiceClient is the client API for DiscoveryProtoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// User service definition
type DiscoveryProtoServiceClient interface {
	Discovery(ctx context.Context, in *DiscoveryServiceRequest, opts ...grpc.CallOption) (*DiscoveryServiceResponse, error)
}

type discoveryProtoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiscoveryProtoServiceClient(cc grpc.ClientConnInterface) DiscoveryProtoServiceClient {
	return &discoveryProtoServiceClient{cc}
}

func (c *discoveryProtoServiceClient) Discovery(ctx context.Context, in *DiscoveryServiceRequest, opts ...grpc.CallOption) (*DiscoveryServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscoveryServiceResponse)
	err := c.cc.Invoke(ctx, DiscoveryProtoService_Discovery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscoveryProtoServiceServer is the server API for DiscoveryProtoService service.
// All implementations must embed UnimplementedDiscoveryProtoServiceServer
// for forward compatibility.
//
// User service definition
type DiscoveryProtoServiceServer interface {
	Discovery(context.Context, *DiscoveryServiceRequest) (*DiscoveryServiceResponse, error)
	mustEmbedUnimplementedDiscoveryProtoServiceServer()
}

// UnimplementedDiscoveryProtoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiscoveryProtoServiceServer struct{}

func (UnimplementedDiscoveryProtoServiceServer) Discovery(context.Context, *DiscoveryServiceRequest) (*DiscoveryServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Discovery not implemented")
}
func (UnimplementedDiscoveryProtoServiceServer) mustEmbedUnimplementedDiscoveryProtoServiceServer() {}
func (UnimplementedDiscoveryProtoServiceServer) testEmbeddedByValue()                               {}

// UnsafeDiscoveryProtoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiscoveryProtoServiceServer will
// result in compilation errors.
type UnsafeDiscoveryProtoServiceServer interface {
	mustEmbedUnimplementedDiscoveryProtoServiceServer()
}

func RegisterDiscoveryProtoServiceServer(s grpc.ServiceRegistrar, srv DiscoveryProtoServiceServer) {
	// If the following call pancis, it indicates UnimplementedDiscoveryProtoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DiscoveryProtoService_ServiceDesc, srv)
}

func _DiscoveryProtoService_Discovery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoveryServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryProtoServiceServer).Discovery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryProtoService_Discovery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryProtoServiceServer).Discovery(ctx, req.(*DiscoveryServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DiscoveryProtoService_ServiceDesc is the grpc.ServiceDesc for DiscoveryProtoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiscoveryProtoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "discovery.DiscoveryProtoService",
	HandlerType: (*DiscoveryProtoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Discovery",
			Handler:    _DiscoveryProtoService_Discovery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "discovery.proto",
}
