// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: gateway.proto

package __

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// GatewayProtoServiceClient is the client API for GatewayProtoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Gateway service definition
type GatewayProtoServiceClient interface {
}

type gatewayProtoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayProtoServiceClient(cc grpc.ClientConnInterface) GatewayProtoServiceClient {
	return &gatewayProtoServiceClient{cc}
}

// GatewayProtoServiceServer is the server API for GatewayProtoService service.
// All implementations must embed UnimplementedGatewayProtoServiceServer
// for forward compatibility.
//
// Gateway service definition
type GatewayProtoServiceServer interface {
	mustEmbedUnimplementedGatewayProtoServiceServer()
}

// UnimplementedGatewayProtoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayProtoServiceServer struct{}

func (UnimplementedGatewayProtoServiceServer) mustEmbedUnimplementedGatewayProtoServiceServer() {}
func (UnimplementedGatewayProtoServiceServer) testEmbeddedByValue()                             {}

// UnsafeGatewayProtoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayProtoServiceServer will
// result in compilation errors.
type UnsafeGatewayProtoServiceServer interface {
	mustEmbedUnimplementedGatewayProtoServiceServer()
}

func RegisterGatewayProtoServiceServer(s grpc.ServiceRegistrar, srv GatewayProtoServiceServer) {
	// If the following call pancis, it indicates UnimplementedGatewayProtoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayProtoService_ServiceDesc, srv)
}

// GatewayProtoService_ServiceDesc is the grpc.ServiceDesc for GatewayProtoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayProtoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.GatewayProtoService",
	HandlerType: (*GatewayProtoServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "gateway.proto",
}
