// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: order.proto

package __

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// OrderProtoServiceClient is the client API for OrderProtoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Order service definition
type OrderProtoServiceClient interface {
}

type orderProtoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderProtoServiceClient(cc grpc.ClientConnInterface) OrderProtoServiceClient {
	return &orderProtoServiceClient{cc}
}

// OrderProtoServiceServer is the server API for OrderProtoService service.
// All implementations must embed UnimplementedOrderProtoServiceServer
// for forward compatibility.
//
// Order service definition
type OrderProtoServiceServer interface {
	mustEmbedUnimplementedOrderProtoServiceServer()
}

// UnimplementedOrderProtoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderProtoServiceServer struct{}

func (UnimplementedOrderProtoServiceServer) mustEmbedUnimplementedOrderProtoServiceServer() {}
func (UnimplementedOrderProtoServiceServer) testEmbeddedByValue()                           {}

// UnsafeOrderProtoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderProtoServiceServer will
// result in compilation errors.
type UnsafeOrderProtoServiceServer interface {
	mustEmbedUnimplementedOrderProtoServiceServer()
}

func RegisterOrderProtoServiceServer(s grpc.ServiceRegistrar, srv OrderProtoServiceServer) {
	// If the following call pancis, it indicates UnimplementedOrderProtoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderProtoService_ServiceDesc, srv)
}

// OrderProtoService_ServiceDesc is the grpc.ServiceDesc for OrderProtoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderProtoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.OrderProtoService",
	HandlerType: (*OrderProtoServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "order.proto",
}
