// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: pair.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pair) Reset() {
	*x = Pair{}
	mi := &file_pair_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pair) ProtoMessage() {}

func (x *Pair) ProtoReflect() protoreflect.Message {
	mi := &file_pair_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pair.ProtoReflect.Descriptor instead.
func (*Pair) Descriptor() ([]byte, []int) {
	return file_pair_proto_rawDescGZIP(), []int{0}
}

func (x *Pair) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPairsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPairsRequest) Reset() {
	*x = GetPairsRequest{}
	mi := &file_pair_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPairsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPairsRequest) ProtoMessage() {}

func (x *GetPairsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pair_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPairsRequest.ProtoReflect.Descriptor instead.
func (*GetPairsRequest) Descriptor() ([]byte, []int) {
	return file_pair_proto_rawDescGZIP(), []int{1}
}

func (x *GetPairsRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type GetPairsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pairs         []*Pair                `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPairsResponse) Reset() {
	*x = GetPairsResponse{}
	mi := &file_pair_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPairsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPairsResponse) ProtoMessage() {}

func (x *GetPairsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pair_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPairsResponse.ProtoReflect.Descriptor instead.
func (*GetPairsResponse) Descriptor() ([]byte, []int) {
	return file_pair_proto_rawDescGZIP(), []int{2}
}

func (x *GetPairsResponse) GetPairs() []*Pair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

type GetPairRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PairId        string                 `protobuf:"bytes,1,opt,name=pair_id,json=pairId,proto3" json:"pair_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPairRequest) Reset() {
	*x = GetPairRequest{}
	mi := &file_pair_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPairRequest) ProtoMessage() {}

func (x *GetPairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pair_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPairRequest.ProtoReflect.Descriptor instead.
func (*GetPairRequest) Descriptor() ([]byte, []int) {
	return file_pair_proto_rawDescGZIP(), []int{3}
}

func (x *GetPairRequest) GetPairId() string {
	if x != nil {
		return x.PairId
	}
	return ""
}

type GetPairResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pair          *Pair                  `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPairResponse) Reset() {
	*x = GetPairResponse{}
	mi := &file_pair_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPairResponse) ProtoMessage() {}

func (x *GetPairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pair_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPairResponse.ProtoReflect.Descriptor instead.
func (*GetPairResponse) Descriptor() ([]byte, []int) {
	return file_pair_proto_rawDescGZIP(), []int{4}
}

func (x *GetPairResponse) GetPair() *Pair {
	if x != nil {
		return x.Pair
	}
	return nil
}

type PostPairRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pair          *Pair                  `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostPairRequest) Reset() {
	*x = PostPairRequest{}
	mi := &file_pair_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostPairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostPairRequest) ProtoMessage() {}

func (x *PostPairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pair_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostPairRequest.ProtoReflect.Descriptor instead.
func (*PostPairRequest) Descriptor() ([]byte, []int) {
	return file_pair_proto_rawDescGZIP(), []int{5}
}

func (x *PostPairRequest) GetPair() *Pair {
	if x != nil {
		return x.Pair
	}
	return nil
}

type PostPairResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pair          *Pair                  `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostPairResponse) Reset() {
	*x = PostPairResponse{}
	mi := &file_pair_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostPairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostPairResponse) ProtoMessage() {}

func (x *PostPairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pair_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostPairResponse.ProtoReflect.Descriptor instead.
func (*PostPairResponse) Descriptor() ([]byte, []int) {
	return file_pair_proto_rawDescGZIP(), []int{6}
}

func (x *PostPairResponse) GetPair() *Pair {
	if x != nil {
		return x.Pair
	}
	return nil
}

type PutPairRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pair          *Pair                  `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutPairRequest) Reset() {
	*x = PutPairRequest{}
	mi := &file_pair_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutPairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutPairRequest) ProtoMessage() {}

func (x *PutPairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pair_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutPairRequest.ProtoReflect.Descriptor instead.
func (*PutPairRequest) Descriptor() ([]byte, []int) {
	return file_pair_proto_rawDescGZIP(), []int{7}
}

func (x *PutPairRequest) GetPair() *Pair {
	if x != nil {
		return x.Pair
	}
	return nil
}

type PutPairResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pair          *Pair                  `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutPairResponse) Reset() {
	*x = PutPairResponse{}
	mi := &file_pair_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutPairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutPairResponse) ProtoMessage() {}

func (x *PutPairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pair_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutPairResponse.ProtoReflect.Descriptor instead.
func (*PutPairResponse) Descriptor() ([]byte, []int) {
	return file_pair_proto_rawDescGZIP(), []int{8}
}

func (x *PutPairResponse) GetPair() *Pair {
	if x != nil {
		return x.Pair
	}
	return nil
}

type DeletePairRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PairId        string                 `protobuf:"bytes,1,opt,name=pair_id,json=pairId,proto3" json:"pair_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePairRequest) Reset() {
	*x = DeletePairRequest{}
	mi := &file_pair_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePairRequest) ProtoMessage() {}

func (x *DeletePairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pair_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePairRequest.ProtoReflect.Descriptor instead.
func (*DeletePairRequest) Descriptor() ([]byte, []int) {
	return file_pair_proto_rawDescGZIP(), []int{9}
}

func (x *DeletePairRequest) GetPairId() string {
	if x != nil {
		return x.PairId
	}
	return ""
}

type DeletePairResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePairResponse) Reset() {
	*x = DeletePairResponse{}
	mi := &file_pair_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePairResponse) ProtoMessage() {}

func (x *DeletePairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pair_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePairResponse.ProtoReflect.Descriptor instead.
func (*DeletePairResponse) Descriptor() ([]byte, []int) {
	return file_pair_proto_rawDescGZIP(), []int{10}
}

func (x *DeletePairResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PostValidatePairRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pair          *Pair                  `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostValidatePairRequest) Reset() {
	*x = PostValidatePairRequest{}
	mi := &file_pair_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostValidatePairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostValidatePairRequest) ProtoMessage() {}

func (x *PostValidatePairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pair_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostValidatePairRequest.ProtoReflect.Descriptor instead.
func (*PostValidatePairRequest) Descriptor() ([]byte, []int) {
	return file_pair_proto_rawDescGZIP(), []int{11}
}

func (x *PostValidatePairRequest) GetPair() *Pair {
	if x != nil {
		return x.Pair
	}
	return nil
}

type PostValidatePairResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostValidatePairResponse) Reset() {
	*x = PostValidatePairResponse{}
	mi := &file_pair_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostValidatePairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostValidatePairResponse) ProtoMessage() {}

func (x *PostValidatePairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pair_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostValidatePairResponse.ProtoReflect.Descriptor instead.
func (*PostValidatePairResponse) Descriptor() ([]byte, []int) {
	return file_pair_proto_rawDescGZIP(), []int{12}
}

func (x *PostValidatePairResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_pair_proto protoreflect.FileDescriptor

const file_pair_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"pair.proto\x12\x04pair\"\x16\n" +
	"\x04Pair\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\",\n" +
	"\x0fGetPairsRequest\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\"4\n" +
	"\x10GetPairsResponse\x12 \n" +
	"\x05pairs\x18\x01 \x03(\v2\n" +
	".pair.PairR\x05pairs\")\n" +
	"\x0eGetPairRequest\x12\x17\n" +
	"\apair_id\x18\x01 \x01(\tR\x06pairId\"1\n" +
	"\x0fGetPairResponse\x12\x1e\n" +
	"\x04pair\x18\x01 \x01(\v2\n" +
	".pair.PairR\x04pair\"1\n" +
	"\x0fPostPairRequest\x12\x1e\n" +
	"\x04pair\x18\x01 \x01(\v2\n" +
	".pair.PairR\x04pair\"2\n" +
	"\x10PostPairResponse\x12\x1e\n" +
	"\x04pair\x18\x01 \x01(\v2\n" +
	".pair.PairR\x04pair\"0\n" +
	"\x0ePutPairRequest\x12\x1e\n" +
	"\x04pair\x18\x01 \x01(\v2\n" +
	".pair.PairR\x04pair\"1\n" +
	"\x0fPutPairResponse\x12\x1e\n" +
	"\x04pair\x18\x01 \x01(\v2\n" +
	".pair.PairR\x04pair\",\n" +
	"\x11DeletePairRequest\x12\x17\n" +
	"\apair_id\x18\x01 \x01(\tR\x06pairId\".\n" +
	"\x12DeletePairResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"9\n" +
	"\x17PostValidatePairRequest\x12\x1e\n" +
	"\x04pair\x18\x01 \x01(\v2\n" +
	".pair.PairR\x04pair\"4\n" +
	"\x18PostValidatePairResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x98\x03\n" +
	"\x10PairProtoService\x12;\n" +
	"\bGetPairs\x12\x15.pair.GetPairsRequest\x1a\x16.pair.GetPairsResponse\"\x00\x128\n" +
	"\aGetPair\x12\x14.pair.GetPairRequest\x1a\x15.pair.GetPairResponse\"\x00\x12;\n" +
	"\bPostPair\x12\x15.pair.PostPairRequest\x1a\x16.pair.PostPairResponse\"\x00\x128\n" +
	"\aPutPair\x12\x14.pair.PutPairRequest\x1a\x15.pair.PutPairResponse\"\x00\x12A\n" +
	"\n" +
	"DeletePair\x12\x17.pair.DeletePairRequest\x1a\x18.pair.DeletePairResponse\"\x00\x12S\n" +
	"\x10PostValidatePair\x12\x1d.pair.PostValidatePairRequest\x1a\x1e.pair.PostValidatePairResponse\"\x00B\x04Z\x02./b\x06proto3"

var (
	file_pair_proto_rawDescOnce sync.Once
	file_pair_proto_rawDescData []byte
)

func file_pair_proto_rawDescGZIP() []byte {
	file_pair_proto_rawDescOnce.Do(func() {
		file_pair_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pair_proto_rawDesc), len(file_pair_proto_rawDesc)))
	})
	return file_pair_proto_rawDescData
}

var file_pair_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pair_proto_goTypes = []any{
	(*Pair)(nil),                     // 0: pair.Pair
	(*GetPairsRequest)(nil),          // 1: pair.GetPairsRequest
	(*GetPairsResponse)(nil),         // 2: pair.GetPairsResponse
	(*GetPairRequest)(nil),           // 3: pair.GetPairRequest
	(*GetPairResponse)(nil),          // 4: pair.GetPairResponse
	(*PostPairRequest)(nil),          // 5: pair.PostPairRequest
	(*PostPairResponse)(nil),         // 6: pair.PostPairResponse
	(*PutPairRequest)(nil),           // 7: pair.PutPairRequest
	(*PutPairResponse)(nil),          // 8: pair.PutPairResponse
	(*DeletePairRequest)(nil),        // 9: pair.DeletePairRequest
	(*DeletePairResponse)(nil),       // 10: pair.DeletePairResponse
	(*PostValidatePairRequest)(nil),  // 11: pair.PostValidatePairRequest
	(*PostValidatePairResponse)(nil), // 12: pair.PostValidatePairResponse
}
var file_pair_proto_depIdxs = []int32{
	0,  // 0: pair.GetPairsResponse.pairs:type_name -> pair.Pair
	0,  // 1: pair.GetPairResponse.pair:type_name -> pair.Pair
	0,  // 2: pair.PostPairRequest.pair:type_name -> pair.Pair
	0,  // 3: pair.PostPairResponse.pair:type_name -> pair.Pair
	0,  // 4: pair.PutPairRequest.pair:type_name -> pair.Pair
	0,  // 5: pair.PutPairResponse.pair:type_name -> pair.Pair
	0,  // 6: pair.PostValidatePairRequest.pair:type_name -> pair.Pair
	1,  // 7: pair.PairProtoService.GetPairs:input_type -> pair.GetPairsRequest
	3,  // 8: pair.PairProtoService.GetPair:input_type -> pair.GetPairRequest
	5,  // 9: pair.PairProtoService.PostPair:input_type -> pair.PostPairRequest
	7,  // 10: pair.PairProtoService.PutPair:input_type -> pair.PutPairRequest
	9,  // 11: pair.PairProtoService.DeletePair:input_type -> pair.DeletePairRequest
	11, // 12: pair.PairProtoService.PostValidatePair:input_type -> pair.PostValidatePairRequest
	2,  // 13: pair.PairProtoService.GetPairs:output_type -> pair.GetPairsResponse
	4,  // 14: pair.PairProtoService.GetPair:output_type -> pair.GetPairResponse
	6,  // 15: pair.PairProtoService.PostPair:output_type -> pair.PostPairResponse
	8,  // 16: pair.PairProtoService.PutPair:output_type -> pair.PutPairResponse
	10, // 17: pair.PairProtoService.DeletePair:output_type -> pair.DeletePairResponse
	12, // 18: pair.PairProtoService.PostValidatePair:output_type -> pair.PostValidatePairResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pair_proto_init() }
func file_pair_proto_init() {
	if File_pair_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pair_proto_rawDesc), len(file_pair_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pair_proto_goTypes,
		DependencyIndexes: file_pair_proto_depIdxs,
		MessageInfos:      file_pair_proto_msgTypes,
	}.Build()
	File_pair_proto = out.File
	file_pair_proto_goTypes = nil
	file_pair_proto_depIdxs = nil
}
