// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: pnl.proto

package __

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// PnlProtoServiceClient is the client API for PnlProtoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Pnl service definition
type PnlProtoServiceClient interface {
}

type pnlProtoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPnlProtoServiceClient(cc grpc.ClientConnInterface) PnlProtoServiceClient {
	return &pnlProtoServiceClient{cc}
}

// PnlProtoServiceServer is the server API for PnlProtoService service.
// All implementations must embed UnimplementedPnlProtoServiceServer
// for forward compatibility.
//
// Pnl service definition
type PnlProtoServiceServer interface {
	mustEmbedUnimplementedPnlProtoServiceServer()
}

// UnimplementedPnlProtoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPnlProtoServiceServer struct{}

func (UnimplementedPnlProtoServiceServer) mustEmbedUnimplementedPnlProtoServiceServer() {}
func (UnimplementedPnlProtoServiceServer) testEmbeddedByValue()                         {}

// UnsafePnlProtoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PnlProtoServiceServer will
// result in compilation errors.
type UnsafePnlProtoServiceServer interface {
	mustEmbedUnimplementedPnlProtoServiceServer()
}

func RegisterPnlProtoServiceServer(s grpc.ServiceRegistrar, srv PnlProtoServiceServer) {
	// If the following call pancis, it indicates UnimplementedPnlProtoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PnlProtoService_ServiceDesc, srv)
}

// PnlProtoService_ServiceDesc is the grpc.ServiceDesc for PnlProtoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PnlProtoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pnl.PnlProtoService",
	HandlerType: (*PnlProtoServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "pnl.proto",
}
