// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: token.proto

package __

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// TokenProtoServiceClient is the client API for TokenProtoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Token service definition
type TokenProtoServiceClient interface {
}

type tokenProtoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenProtoServiceClient(cc grpc.ClientConnInterface) TokenProtoServiceClient {
	return &tokenProtoServiceClient{cc}
}

// TokenProtoServiceServer is the server API for TokenProtoService service.
// All implementations must embed UnimplementedTokenProtoServiceServer
// for forward compatibility.
//
// Token service definition
type TokenProtoServiceServer interface {
	mustEmbedUnimplementedTokenProtoServiceServer()
}

// UnimplementedTokenProtoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTokenProtoServiceServer struct{}

func (UnimplementedTokenProtoServiceServer) mustEmbedUnimplementedTokenProtoServiceServer() {}
func (UnimplementedTokenProtoServiceServer) testEmbeddedByValue()                           {}

// UnsafeTokenProtoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenProtoServiceServer will
// result in compilation errors.
type UnsafeTokenProtoServiceServer interface {
	mustEmbedUnimplementedTokenProtoServiceServer()
}

func RegisterTokenProtoServiceServer(s grpc.ServiceRegistrar, srv TokenProtoServiceServer) {
	// If the following call pancis, it indicates UnimplementedTokenProtoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TokenProtoService_ServiceDesc, srv)
}

// TokenProtoService_ServiceDesc is the grpc.ServiceDesc for TokenProtoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenProtoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "token.TokenProtoService",
	HandlerType: (*TokenProtoServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "token.proto",
}
