// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: wallet.proto

package __

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// WalletProtoServiceClient is the client API for WalletProtoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Wallet service definition
type WalletProtoServiceClient interface {
}

type walletProtoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletProtoServiceClient(cc grpc.ClientConnInterface) WalletProtoServiceClient {
	return &walletProtoServiceClient{cc}
}

// WalletProtoServiceServer is the server API for WalletProtoService service.
// All implementations must embed UnimplementedWalletProtoServiceServer
// for forward compatibility.
//
// Wallet service definition
type WalletProtoServiceServer interface {
	mustEmbedUnimplementedWalletProtoServiceServer()
}

// UnimplementedWalletProtoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWalletProtoServiceServer struct{}

func (UnimplementedWalletProtoServiceServer) mustEmbedUnimplementedWalletProtoServiceServer() {}
func (UnimplementedWalletProtoServiceServer) testEmbeddedByValue()                            {}

// UnsafeWalletProtoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletProtoServiceServer will
// result in compilation errors.
type UnsafeWalletProtoServiceServer interface {
	mustEmbedUnimplementedWalletProtoServiceServer()
}

func RegisterWalletProtoServiceServer(s grpc.ServiceRegistrar, srv WalletProtoServiceServer) {
	// If the following call pancis, it indicates UnimplementedWalletProtoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WalletProtoService_ServiceDesc, srv)
}

// WalletProtoService_ServiceDesc is the grpc.ServiceDesc for WalletProtoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalletProtoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wallet.WalletProtoService",
	HandlerType: (*WalletProtoServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "wallet.proto",
}
