name: Staticcheck

on:
  push:
    branches: [ main, master, develop, staging, production ]
  pull_request:
    branches: [ main, master, develop, staging, production ]

jobs:
  staticcheck:
    name: Staticcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'
          check-latest: true

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./... 